USE BDCLINICA_EDDY
GO

----------------------------------------------------------------------------------------
--PROCEDIMIENTOS ALMACENADOS

--ELIMINA UN EMPLEADO
CREATE OR ALTER PROCEDURE ELIMINAR_EMPLEADO
	@IDEMPLEADO INT,
	@MSJ VARCHAR(100) OUT

AS BEGIN
DECLARE @ID_MEDICO INT --VARIABLE TOMA EL VALOR DEL ID DEL MEDICO
IF(NOT EXISTS(SELECT * FROM EMPLEADOS WHERE ID_EMPLEADO = @IDEMPLEADO))
	BEGIN
		SET @MSJ = 'EL EMPLEADO NO EXISTE'
	END
ELSE
	BEGIN
		
		SET @ID_MEDICO = (SELECT ID_MEDICO FROM MEDICOS WHERE ID_EMPLEADO = @IDEMPLEADO)--ASIGNA EL ID DEL MEDICO EN LA VARIABLE
		DELETE FROM PLANILLAS WHERE ID_EMPLEADO = @IDEMPLEADO
		DELETE FROM CONSULTAS WHERE ID_MEDICO = @ID_MEDICO
		DELETE FROM AGENDA WHERE ID_MEDICO = @ID_MEDICO
		DELETE FROM MEDICOS WHERE ID_EMPLEADO = @IDEMPLEADO
		DELETE FROM SECRETARIOS WHERE ID_EMPLEADO = @IDEMPLEADO		
		DELETE FROM AUXILIARES WHERE ID_EMPLEADO = @IDEMPLEADO		
		DELETE FROM EMPLEADOS WHERE ID_EMPLEADO = @IDEMPLEADO
		SET @MSJ = 'EMPLEADO ELIMINADO'
		RETURN 1
	END
END
GO