--CREA Y USA LA BASE DE DATOS
CREATE DATABASE BDCLINICA_EDDY
GO
USE BDCLINICA_EDDY
GO

----------------------------------------------------------------------------------------
--CREA LA TABLA EMPLEADOS
CREATE TABLE EMPLEADOS(
	ID_EMPLEADO INT PRIMARY KEY IDENTITY(1,1),
	NUM_CEDULA VARCHAR(10) NOT NULL UNIQUE,
	NUM_CARNET VARCHAR(10) NOT NULL UNIQUE,
	NOMBRE VARCHAR(20) NOT NULL,
	APELLIDO_01 VARCHAR(20) NOT NULL,
	APELLIDO_02 VARCHAR(20) NOT NULL,
	PAIS VARCHAR(20) NOT NULL DEFAULT 'COSTA RICA',
	PROVINCIA VARCHAR(20) NOT NULL DEFAULT 'ALAJUELA',
	SEXO VARCHAR(20) NOT NULL DEFAULT 'NO MENCIONA',
	FECHA_NACIMIENTO DATE NOT NULL,
	ESTADO_CIVIL VARCHAR(10) NOT NULL DEFAULT 'SOLTERO',
	CORREO_ELECTRONICO VARCHAR(30) NOT NULL,
	NUM_TELEFONO VARCHAR(10) NOT NULL,
	ESTADO VARCHAR(3) NOT NULL DEFAULT 'ACT'
)

--REESTRICCIONES TABLA EMPLEADOS
--REVISA PROVINCIA IGUAL A SAN JOSE, ALAJUELA...
ALTER TABLE EMPLEADOS ADD CONSTRAINT CHK_PROVINCIAS_EMP
	CHECK (PROVINCIA LIKE 'SAN JOSE' OR PROVINCIA LIKE 'ALAJUELA' OR PROVINCIA LIKE 'CARTAGO' OR PROVINCIA LIKE 'HEREDIA' OR PROVINCIA LIKE 'PUNTARENAS' OR PROVINCIA LIKE 'LIMON' OR PROVINCIA LIKE 'GUANACASTE')

--REVISA SEXO IGUAL A MASCULINO, FEMENINO...
ALTER TABLE EMPLEADOS ADD CONSTRAINT CHK_SEXO_EMP
	CHECK (SEXO LIKE 'MASCULINO' OR SEXO LIKE 'FEMENINO' OR SEXO LIKE 'NO MENCIONA')

--REVISA FECHA DE NACIMIENTO SEA MENOR A LA ACTUAL
ALTER TABLE EMPLEADOS ADD CONSTRAINT CHK_FECHANAC_EMP
	CHECK (FECHA_NACIMIENTO < GETDATE())

--REVISA ESTADO CIVIL IGUAL A SOLTERO, CASADO...
ALTER TABLE EMPLEADOS ADD CONSTRAINT CHK_ESTADOCIVIL_EMP
	CHECK (ESTADO_CIVIL LIKE 'SOLTERO' OR ESTADO_CIVIL LIKE 'CASADO' OR ESTADO_CIVIL LIKE 'DIVORCIADO' OR ESTADO_CIVIL LIKE 'VIUDO')

--REVISA ESTADO IGUAL A ACT O INA
ALTER TABLE EMPLEADOS ADD CONSTRAINT CHK_ESTADO_EMP
	CHECK (ESTADO LIKE 'ACT' OR ESTADO LIKE 'INA')

----------------------------------------------------------------------------------------
--CREA LA TABLA PACIENTES
CREATE TABLE PACIENTES(
	ID_PACIENTE INT PRIMARY KEY IDENTITY(1,1),
	NUM_CEDULA VARCHAR(10) NOT NULL UNIQUE,
	NOMBRE VARCHAR(20) NOT NULL UNIQUE,
	APELLIDO_01 VARCHAR(20) NOT NULL,
	APELLIDO_02 VARCHAR(20) NOT NULL,
	PAIS VARCHAR(20) NOT NULL DEFAULT 'COSTA RICA',
	PROVINCIA VARCHAR(20) NOT NULL DEFAULT 'ALAJUELA',
	SEXO VARCHAR(20) NOT NULL DEFAULT 'NO MENCIONA', 
	FECHA_NACIMIENTO DATE NOT NULL,
	ESTADO_CIVIL VARCHAR(10) NOT NULL DEFAULT 'SOLTERO',
	CORREO_ELECTRONICO VARCHAR(30) NOT NULL,
	NUM_TELEFONO VARCHAR(10) NOT NULL,
	TIPO_SANGRE VARCHAR(10) NOT NULL,
	ESTADO VARCHAR(3) NOT NULL DEFAULT 'ACT'
)

--REESTRICCIONES TABLA PACIENTES
--REVISA PROVINCIA IGUAL A SAN JOSE, ALAJUELA...
ALTER TABLE PACIENTES ADD CONSTRAINT CHK_PROVINCIAS_PAC
	CHECK (PROVINCIA IN ('SAN JOSE','ALAJUELA','CARTAGO','HEREDIA','PUNTARENAS', 'LIMON','GUANACASTE'))

----REVISA SEXO IGUAL A MASCULINO, FEMENINO...
ALTER TABLE PACIENTES ADD CONSTRAINT CHK_SEXO_PAC
	CHECK (SEXO LIKE 'MASCULINO' OR SEXO LIKE 'FEMENINO' OR SEXO LIKE 'NO MENCIONA')

----REVISA ESTADO CIVIL IGUAL A SOLTERO, CASADO...
ALTER TABLE PACIENTES ADD CONSTRAINT CHK_ESTADOCIVIL_PAC
	CHECK (ESTADO_CIVIL LIKE 'SOLTERO' OR ESTADO_CIVIL LIKE 'CASADO' OR ESTADO_CIVIL LIKE 'DIVORCIADO' OR ESTADO_CIVIL LIKE 'VIUDO')

----REVISA ESTADO IGUAL A ACT O INA
ALTER TABLE PACIENTES ADD CONSTRAINT CHK_ESTADO_PAC
	CHECK (ESTADO LIKE 'ACT' OR ESTADO LIKE 'INA')

----------------------------------------------------------------------------------------
--CREA LA TABLA SECRETARIOS
CREATE TABLE SECRETARIOS(
	ID_SECRETARIO INT PRIMARY KEY IDENTITY(1,1),
	ID_EMPLEADO INT NOT NULL
)

----------------------------------------------------------------------------------------
--CREA LA TABLA MÉDICOS
CREATE TABLE MEDICOS(
	ID_MEDICO INT PRIMARY KEY IDENTITY(1,1),
	ID_EMPLEADO INT NOT NULL,
	ESPECIALIDAD VARCHAR(20) NOT NULL,
	NUM_CERTIFICACION VARCHAR(20) NOT NULL
)


----------------------------------------------------------------------------------------
--CREA LA TABLA AUXILIARES
CREATE TABLE AUXILIARES(
	ID_AUXILIAR INT PRIMARY KEY IDENTITY(1,1),
	ID_EMPLEADO INT NOT NULL,
	AREA VARCHAR(20) NOT NULL
)

----------------------------------------------------------------------------------------
--CREA LA TABLA EXPEDIENTES
CREATE TABLE EXPEDIENTES(
	ID_EXPEDIENTE INT PRIMARY KEY IDENTITY(1,1),
	ID_PACIENTE INT NOT NULL,
	FECHA_CREACION DATE NOT NULL
)
 
----------------------------------------------------------------------------------------
--CREA LA TABLA PADECIMIENTOS
CREATE TABLE PADECIMIENTOS(
	ID_PADECIMIENTO INT PRIMARY KEY IDENTITY(1,1),
	ID_EXPEDIENTE INT NOT NULL,
	NOMBRE VARCHAR(30) NOT NULL,
	DESCRIPCION VARCHAR(200) NOT NULL,
	ESTADO VARCHAR(3) NOT NULL
)

--REESTRICCIONES TABLA PADECIMIENTOS
--REVISA ESTADO IGUAL A ACT O INA
ALTER TABLE PADECIMIENTOS ADD CONSTRAINT CHK_ESTADO_PAD
	CHECK (ESTADO LIKE 'ACT' OR ESTADO LIKE 'INA')

----------------------------------------------------------------------------------------
--CREA LA TABLA AGENDA
CREATE TABLE AGENDA(
	ID_AGENDA INT PRIMARY KEY IDENTITY(1,1),
	ID_MEDICO INT NOT NULL,
	DIAS_SEMANA VARCHAR(20) NOT NULL,
	HORA_ENTRADA TIME NOT NULL,
	HORA_SALIDA TIME NOT NULL,
)

--REESTRICCIONES TABLA AGENDA
--REVISA QUE EL HORARIO DEL MEDICO COINCIDA CON EL DE LA CLINICA
ALTER TABLE AGENDA ADD CONSTRAINT CHK_HORARIO
	CHECK (HORA_ENTRADA >= '7:00' AND HORA_SALIDA <= '17:00')


----------------------------------------------------------------------------------------
--CREA LA TABLA CONSULTAS
CREATE TABLE CONSULTAS(
	ID_CONSULTA INT PRIMARY KEY IDENTITY(1,1),
	ID_MEDICO INT NOT NULL,
	ID_PACIENTE INT NOT NULL,
	DIA DATE NOT NULL,
	HORA TIME NOT NULL,
	MOTIVO VARCHAR(200) NOT NULL
)

----------------------------------------------------------------------------------------
--CREA LA TABLA HISTORIAL_CITAS
CREATE TABLE HISTORIAL_CITAS(
	ID_HISTORIAL_CITAS INT PRIMARY KEY IDENTITY(1,1),
	ID_EXPEDIENTE INT NOT NULL,
	FECHA DATE NOT NULL, 
	HORA TIME NOT NULL,
	ID_MEDICO_RESPONSABLE INT NOT NULL,
	MOTIVO VARCHAR(200) NOT NULL
)
----------------------------------------------------------------------------------------
--CREA LA TABLA TRATAMIENTOS
CREATE TABLE TRATAMIENTOS(
	ID_TRATAMIENTO INT PRIMARY KEY IDENTITY(1,1),
	ID_PADECIMIENTO INT NOT NULL,
	NOMBRE VARCHAR(30) NOT NULL,
	DOSIS VARCHAR(100) NOT NULL,
	DURACION VARCHAR(100) NOT NULL,
	ESTADO VARCHAR(3) NOT NULL
)


--REESTRICCIONES TABLA TRATAMIENTOS
--REVISA ESTADO IGUAL A ACT O INA
ALTER TABLE TRATAMIENTOS ADD CONSTRAINT CHK_ESTADO_TRA
	CHECK (ESTADO LIKE 'ACT' OR ESTADO LIKE 'INA')

----------------------------------------------------------------------------------------
--CREA LA TABLA PLANILLAS
CREATE TABLE PLANILLAS(
	ID_PLANILLA INT PRIMARY KEY IDENTITY(1,1),
	ID_EMPLEADO INT NOT NULL,
	SALARIO_BRUTO DECIMAL NOT NULL,
	EXTRAS DECIMAL NOT NULL,
	DEDUCCIONES DECIMAL NOT NULL,
	SALARIO_TOTAL DECIMAL NOT NULL
)
----------------------------------------------------------------------------------------
--CREA LA TABLA PAGOS
CREATE TABLE PAGOS(
	ID_PAGO INT PRIMARY KEY IDENTITY(1,1),
	ID_PACIENTE INT NOT NULL,
	MONTO DECIMAL NOT NULL,
	METODO_PAGO VARCHAR(10) NOT NULL,
	ESTADO VARCHAR(10) NOT NULL
)

--REESTRICCIONES TABLA PAGOS
--REVISA ESTADO IGUAL A PEN O CAN
ALTER TABLE PAGOS ADD CONSTRAINT CHK_ESTADO_PAG
	CHECK (ESTADO LIKE 'PEN' OR ESTADO LIKE 'CAN')

----------------------------------------------------------------------------------------
--CREA LA TABLA USUARIO_INGRESO
CREATE TABLE USUARIO_INGRESO(
	ID_USUARIO INT PRIMARY KEY IDENTITY(1,1),
	ID_PACIENTE INT NOT NULL,
	CORREO_ELECTRONICO VARCHAR(30) NOT NULL,
	CONTRASENA VARCHAR(10) NOT NULL
)
----------------------------------------------------------------------------------------
--RELACIONES

--DE PADECIMIENTOS A TRATAMIENTOS
ALTER TABLE TRATAMIENTOS ADD CONSTRAINT FK_ID_PADECIMIENTO_TRA
	FOREIGN KEY(ID_PADECIMIENTO) REFERENCES PADECIMIENTOS(ID_PADECIMIENTO)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION

--DE EXPEDIENTES A HISTORIAL CITAS
ALTER TABLE HISTORIAL_CITAS ADD CONSTRAINT FK_ID_EXPEDIENTE_EX
	FOREIGN KEY(ID_EXPEDIENTE) REFERENCES EXPEDIENTES(ID_EXPEDIENTE)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION

--DE EXPEDIENTES A PADECIMIENTOS
ALTER TABLE PADECIMIENTOS ADD CONSTRAINT FK_ID_EXPEDIENTE_PAD
	FOREIGN KEY(ID_EXPEDIENTE) REFERENCES EXPEDIENTES(ID_EXPEDIENTE)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION

--DE PACIENTES A EXPEDIENTES
ALTER TABLE EXPEDIENTES ADD CONSTRAINT FK_ID_PACIENTE_PAC
	FOREIGN KEY(ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION

--DE PACIENTES A CONSULTAS
ALTER TABLE CONSULTAS ADD CONSTRAINT FK_ID_PACIENTE_CONS
	FOREIGN KEY(ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION

--DE PACIENTES A PAGOS
ALTER TABLE PAGOS ADD CONSTRAINT FK_ID_PACIENTE_PACI
	FOREIGN KEY(ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION

--DE EMPLEADOS A PLANILLAS
ALTER TABLE PLANILLAS ADD CONSTRAINT FK_ID_EMPLEADO_PLA
	FOREIGN KEY(ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION

--DE EMPLEADOS A SECRETARIOS 
ALTER TABLE SECRETARIOS ADD CONSTRAINT FK_ID_EMPLEADO_SEC
	FOREIGN KEY(ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION

--DE EMPLEADOS A AUXILIARES
ALTER TABLE AUXILIARES ADD CONSTRAINT FK_ID_EMPLEADO_AUX
	FOREIGN KEY(ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION

--DE EMPLEADOS A MEDICOS 
ALTER TABLE MEDICOS ADD CONSTRAINT FK_ID_EMPLEADO_MED
	FOREIGN KEY(ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION

--DE MEDICOS A AGENDA
ALTER TABLE AGENDA ADD CONSTRAINT FK_ID_MEDICO_AGE
	FOREIGN KEY(ID_MEDICO) REFERENCES MEDICOS(ID_MEDICO)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION

--DE MEDICOS A CONSULTAS
ALTER TABLE CONSULTAS ADD CONSTRAINT FK_ID_MEDICO_CON
	FOREIGN KEY(ID_MEDICO) REFERENCES MEDICOS(ID_MEDICO)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION

--DE PACIENTES A USUARIO_INGRESO
ALTER TABLE USUARIO_INGRESO ADD CONSTRAINT FK_ID_PACIENTE_UI
	FOREIGN KEY(ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION




